### ISSUE TITLE
brcmfmac firmware for 43456 chip (found in e.g. Pinebook Pro)

### ISSUE THREAD

**Issue by rathann** [Infineon/ifx-linux-firmware#1]
**Is your feature request related to a problem? Please describe.**

Official brcmfmac firmware for 43456 chip is missing. There are some firmwares for this chip floating around the internet, but their origin is unknown and it's crashing the kernel (5.11.12).

**Describe the solution you'd like**

I'd like Cypress to submit official firmware for this chip to Linux kernel upstream or at least provide it here under a redistributable license so that it can be included in Linux distributions like Fedora.

**Describe alternatives you've considered**

Swapping a different Wi-Fi chip would be alternative, but it'd be best if the Wi-Fi in the Pinebook Pro worked out-of-the-box.

**Additional context**

Here's the dmesg output with the firmware from [Manjaro](https://gitlab.manjaro.org/tsys/pinebook-firmware/-/tree/master/brcm):
```
[ 5138.535243] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43456-sdio for chip BCM4345/9
[ 5138.536167] usbcore: registered new interface driver brcmfmac
[ 5138.631278] brcmfmac: brcmf_fw_alloc_request: using brcm/brcmfmac43456-sdio for chip BCM4345/9
[ 5138.643612] brcmfmac: brcmf_c_preinit_dcmds: Firmware: BCM4345/9 wl0: Jun 16 2017 12:38:26 version 7.45.96.2 (66c4e21@sh-git) (r) FWID 01-1813af84
```

**Comment by 0xraks** [comment]
Hey, the 43456 chip is owned by Broadcom, so I think you can get in touch with them.
[BCM43456-product link](https://www.broadcom.com/products/wireless/wireless-lan-bluetooth/bcm43456)

**Comment by rathann** [comment]
There doesn't seem to be a straightforward way of contacting them, but I'll keep searching. Thanks for the quick response and the link, closing.

**Comment by eshattow** [comment]
Arend says it's Synaptics (not Broadcom) https://lore.kernel.org/linux-firmware/b8a9d845-7289-190e-90ec-849d33721c7d@broadcom.com/
